version: '3.5'

services:
    alpinefull:
        build:
            args:
                CONTAINER_VERSION: 1.0.2
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180217
            cache_from:
                - base_container:20180217
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        container_name: alpinefull
        environment:
            CONTAINER_NAME: alpinefull
        image: alpinefull:20180217
        hostname: alpinefull
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
        volumes:
                - ./vols-rw/opt:/opt

