version: '3.2'

services:
    alpinefull:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
            context: .
        container_name: alpinefull
        image: alpinefull:20180210
        hostname: alpinefull
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
        volumes:
                - ./vols-rw/opt:/opt
