version: '3.3'

services:
    alpinefull:
        build:
            args:
                CBF_VERSION: ${CBF_VERSION:-}
                CONTAINER_NAME: alpinefull
                FROM_BASE: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}base_container:${BASE_TAG:-latest}
            cache_from:
                - ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}alpine:3.8
                - ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}base_container:${BASE_TAG:-latest}
            context: .
            dockerfile: Dockerfile
            labels:
                container.fingerprint: $CONTAINER_FINGERPRINT
                container.git.refs: $CONTAINER_GIT_REFS
                container.git.commit: $CONTAINER_GIT_COMMIT
                container.git.url: $CONTAINER_GIT_URL
                container.origin: $CONTAINER_ORIGIN
                container.orginal.name: alpinefull
        container_name: alpinefull
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: alpinefull
        image: ${DOCKER_REGISTRY:-}${CONTAINER_OS:-}alpinefull:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        volumes:
            - ./vols-rw/opt:/opt
