version: '3.3'

services:
    alpinefull:
        build:
            args:
                CBF_VERSION: "${CBF_VERSION:-}"
                CONTAINER_NAME: alpinefull
                CONTAINER_VERSION: ${CONTAINER_VERSION:-3.0.0}
                FROM_BASE: base_container:${CONTAINER_TAG:-latest}
            cache_from:
                - alpine:3.8
                - base_container:${CONTAINER_TAG:-latest}
            context: .
            dockerfile: Dockerfile
        container_name: alpinefull
        environment:
            DEBUG_TRACE: ${DEBUG_TRACE:-0}
        hostname: alpinefull
        image: alpinefull:${CONTAINER_TAG:-latest}
        logging:
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        volumes:
            - ./vols-rw/opt:/opt

