version: '3.5'

services:
    alpinefull:
        build:
            args:
                CODE_VERSION: base_container:20180210
            cache_from:
                - base_container:20180210
                - alpine:3.6                 
            context: .
        container_name: alpinefull
        depends_on:
            - base
        image: alpinefull:20180210
        hostname: alpinefull
        logging:
            driver: "json-file"
            options:
                max-size: "10m"
        volumes:
                - ./vols-rw/opt:/opt


    base:
        build:
            args:
                CODE_VERSION: alpine:3.6
                TZ: "America/New_York"
            cache_from:
                - alpine:3.6
            context: ../base_container
        image: base_container:20180210
