version: '3.5'

services:
    alpinefull:
        build:
            args:
                CONTAINER_NAME: alpinefull
                CONTAINER_VERSION: 1.0.8
                DEBUG_TRACE: 0
                FROM_BASE: base_container:20180329
            cache_from:
                - base_container:20180329
                - alpine:3.6                 
            context: .
            dockerfile: Dockerfile
        container_name: alpinefull
        image: alpinefull:20180329
        hostname: alpinefull
            driver: json-file
            options:
                max-file: "3"
                max-size: "10m"
        volumes:
            - ./vols-rw/opt:/opt

